stages:
  - clean
  - build
  - test
  - integration_test
  - war

clean:
  script:
  - chmod +x gradlew
  - ./gradlew 
  except:
  - /^(wip|test).*$/

test:
  script:
  - chmod +x gradlew
  - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: [build/test-results/test/TEST-*.xml, build/test-results/integrationTest/TEST-*.xml]
  except:
  - /^(wip|test).*$/
  
integration_test:
  script:
  - chmod +x gradlew
  - ./gradlew integrationTest
  artifacts:
    when: always
    reports:
      junit: [build/test-results/test/TEST-*.xml, build/test-results/integrationTest/TEST-*.xml]
  except:
  - /^(wip|test).*$/

war:
  script:
  - chmod +x gradlew
  - ./gradlew war
  except:
  - /^(wip|test).*$/