.base:
  except:
  - /^(wip|test).*$/

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG


stages:
  - test
  - build
  - staging
  - integrationTest
  - deploy

clean:
  extends: .base
  stage: build
  script:
  - ./gradlew clean

test:
  extends: .base
  stage: test
  script:
  - ./gradlew test -i
  artifacts:
    when: always
    reports:
      junit: [build/test-results/test/TEST-*.xml]

lint:
  extends: .base
  stage: test
  script:
    - ./gradlew ktlintCheck
  allow_failure: true

war:
  extends: .base
  stage: build
  script:
    - ./gradlew war
    - cp ./build/libs/tepid*.war ~/tepid.war
  artifacts:
    when: always
    paths:
      - ./build/libs/tepid*.war

build docker:
  extends: .base
  stage: build
  tags:
    - docker
  before_script:
    - sudo -g docker docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - sudo -g docker docker build -t $CONTAINER_TEST_IMAGE .
    - sudo -g docker docker push $CONTAINER_IMAGE

staging:
  extends: .base
  stage: staging
  script:
    - cp ~/tepid.war /var/lib/tomcat8/webapps/

integrationTest:
  extends: .base
  when: delayed
  start_in: 1 minutes
  stage: integrationTest
  script:
  - ./gradlew integrationTest -i
  artifacts:
    when: always
    reports:
      junit: [build/test-results/integrationTest/TEST-*.xml]


