.base:
  except:
  - /^(wip|test).*$/

stages:
  - build
  - test
  - deploy

clean:
  extends: .base
  stage: build
  script:
  - chmod +x gradlew
  - ./gradlew clean

test:
  extends: .base
  stage: test
  script:
  - chmod +x gradlew
  - ./gradlew test -i
  artifacts:
    when: always
    reports:
      junit: [build/test-results/test/TEST-*.xml]
  
integration_test:
  extends: .base
  stage: test
  script:
  - chmod +x gradlew
  - ./gradlew integrationTest -i
  artifacts:
    when: always
    reports:
      junit: [build/test-results/integrationTest/TEST-*.xml]

war:
  extends: .base
  stage: deploy
  script:
  - chmod +x gradlew
  - ./gradlew war
  - cp ./build/libs/tepid*.war ~/tepid.war
  artifacts:
    when: always
    paths:
    - ./build/libs/tepid*.war
    
staging:
  extends: .base
  stage: deploy
  script:
  - cp ~/tepid.war /var/lib/tomcat8/webapps/
  artifacts:
    when: always
    paths:
    - ~/tepid*.war