.base:
  except:
  - /^(wip|test).*$/

stages:
  - test
  - build
  - staging
  - integrationTest
  - deploy

clean:
  extends: .base
  stage: build
  script:
  - ./gradlew clean

test:
  extends: .base
  stage: test
  script:
  - ./gradlew test -i
  artifacts:
    when: always
    reports:
      junit: [build/test-results/test/TEST-*.xml]

lint:
  extends: .base
  stage: test
  script:
    - ./gradlew ktlintCheck
  allow_failure: true

war:
  extends: .base
  stage: build
  script:
    - ./gradlew war
    - cp ./build/libs/tepid*.war ~/tepid.war
  artifacts:
    when: always
    paths:
      - ./build/libs/tepid*.war
staging:
  extends: .base
  stage: staging
  script:
    - cp ~/tepid.war /var/lib/tomcat8/webapps/

integrationTest:
  extends: .base
  when: delayed
  start_in: 1 minutes
  stage: integrationTest
  script:
  - ./gradlew integrationTest -i
  artifacts:
    when: always
    reports:
      junit: [build/test-results/integrationTest/TEST-*.xml]


