stages:
  - build
  - test
  - deploy

clean:
  stage: build
  script:
  - chmod +x gradlew
  - ./gradlew 
  except:
  - /^(wip|test).*$/

test:
  stage: test
  script:
  - chmod +x gradlew
  - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: [build/test-results/test/TEST-*.xml]
  except:
  - /^(wip|test).*$/
  
integration_test:
  stage: test
  script:
  - chmod +x gradlew
  - ./gradlew integrationTest
  artifacts:
    when: always
    reports:
      junit: [build/test-results/integrationTest/TEST-*.xml]
  except:
  - /^(wip|test).*$/

war:
  stage: deploy
  script:
  - chmod +x gradlew
  - ./gradlew war
  - mv ./build/libs/tepid.war ~/tepid.war
  except:
  - /^(wip|test).*$/
  artifacts:
    when: always
    paths:
    - ~/tepid.war
    
staging:
  stage: deploy
  script:
  - cp ~/tepid.war /var/lib/tomcat8/webapps
  artifacts:
    when: always
    paths:
    - ~/tepid.war