prettyPrint: true
openAPI:
  info:
    version: '1.01.00'
    title: TEPID
    description: 'The API for the TEPID Print server by the McGill Science Computer TaskForce. Tell us what we can do better on [github](https://github.com/ctf/tepid-server/).'